version: "3.7"

services:
  ${PROJECT_ARTIFACT}-config:
    image: dperezcabrera/spring-cloud-config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    ports:
      - 8888:8888
    volumes:
      - ${CONFIG_DIR}:/config
    networks:
      - ${PROJECT_ARTIFACT}-net

  ${PROJECT_ARTIFACT}-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ${PROJECT_ARTIFACT}
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
    volumes:
      - ${PROJECT_ARTIFACT}-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ${PROJECT_ARTIFACT}-net

volumes:
  ${PROJECT_ARTIFACT}-postgres-data:

networks:
  ${PROJECT_ARTIFACT}-net:
