version: "3.7"

services:
  test-web:
    image: dperezcabrera/${PROJECT_ARTIFACT}
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://test-postgres:5432/${PROJECT_ARTIFACT}"
      JDBC_DATABASE_USERNAME: ${DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
    ports:
      - 8080:8080
    depends_on:
      - test-postgres 
    networks:
      - test-net

  test-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ${PROJECT_ARTIFACT}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - test-net

volumes:
  test-postgres-data:

networks:
  test-net:
